name: hornet-finder

services:
  hornet-finder-api:
    build: ./backend
    container_name: hornet-finder-api
    image: hornet-finder-api
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - HOST=${HOST}
      - KEYCLOAK_PUBLIC_KEY=${KEYCLOAK_PUBLIC_KEY}
    ports:
      - "8000:8000"
    tty: true

  hornet-finder-keycloak-db:
    image: postgres:latest
    container_name: hornet-finder-keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak-db:/var/lib/postgresql/data
  hornet-finder-keycloak:
    build: ./auth
    container_name: hornet-finder-keycloak
    image: hornet-finder-keycloak
    environment:
      - KC_DB_URL=jdbc:postgresql://hornet-finder-keycloak-db/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
    depends_on:
      - hornet-finder-keycloak-db
    ports:
      - "8080:8080"
  
volumes:
  keycloak-db:
